name: Checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby
        with:
          ruby-version: '2.4'
      - name: install libpq-dev
        run: |
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
          sudo apt update
          sudo apt install libpq-dev cmake -y 
      - name: Install dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec rake test
